### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by dufferzafar** [suem/krunner_autojump_plugin#3]
I am using Kubuntu 15.10 and tried installing this plugin (by running install.sh) and have autojump installed. But it didn't work!

**Comment by suem** [comment]
Hi Dufferzafar,

Unfortunately I didn't have time to keep the plugin supported. Haven't used it myself in over a year. So feel free to fork and fix it if you like :)

Cheers

**Comment by dufferzafar** [comment]
@suem Yeah I would be happy to fix this, since I need it myself. 

I am new to KDE (but have some experience with Python), so can you please tell me what the issue might be?

**Comment by suem** [comment]
Hi,
Sorry for responding so late. 

My suggestion would be that there is some proplem when calling the autojump command and parsing the results. Maybe have a closer look at the python script that handles the interaction.

Keep in mind tough that I wrote this plugin for KDE4, I don't know how much changed in plasma5.
I wrote this plugin by taking some sample code for writing krunner plugins and extending it to communicate with autojump.

**Comment by dufferzafar** [comment]
I'll investigate this (when I have some free time) and let you know about it.

@garvitdelhi Do you use Autojump & KRunner?

**Comment by plusminushalf** [comment]
@dufferzafar yeah, I do you KRunner but haven't tried AutoJump I will give it a try tonight

**Comment by Mte90** [comment]
I did some tests, pykde is not supported anymore so is not possible to use this plugin.

**Comment by suem** [comment]
Hi there, 

I haven't realy been maintaining this project since 2016.
Feel free to make a fork of it to get it working again.

Cheers
